<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Branch;

class BranchSeeder extends Seeder
{
    public function run()
    {
        Branch::truncate();
        
        $branches = [
            [
                'name' => 'الفرع الرئيسي - دمشق',
                'name_ar' => 'الفرع الرئيسي - دمشق',
                'name_en' => 'Main Branch - Damascus',
                'address' => 'شارع الجمهورية، دمشق، سوريا',
                'address_ar' => 'شارع الجمهورية، دمشق، سوريا',
                'address_en' => 'Republic Street, Damascus, Syria',
                'city' => 'دمشق',
                'state' => 'دمشق',
                'country' => 'سوريا',
                'postal_code' => '10001',
                'phone' => '+963-11-1234567',
                'email' => 'damascus@magicshoe.test',
                'manager_name' => 'أحمد محمد',
                'manager_phone' => '+963-11-9876543',
                'manager_email' => 'ahmed@magicshoe.test',
                'latitude' => 33.5138,
                'longitude' => 36.2765,
                'is_active' => true,
                'opening_time' => '09:00',
                'closing_time' => '22:00',
                'working_days' => ['saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            ],
            [
                'name' => 'فرع حلب',
                'name_ar' => 'فرع حلب',
                'name_en' => 'Aleppo Branch',
                'address' => 'شارع الجميلية، حلب، سوريا',
                'address_ar' => 'شارع الجميلية، حلب، سوريا',
                'address_en' => 'Al-Jamiliya Street, Aleppo, Syria',
                'city' => 'حلب',
                'state' => 'حلب',
                'country' => 'سوريا',
                'postal_code' => '21000',
                'phone' => '+963-21-2345678',
                'email' => 'aleppo@magicshoe.test',
                'manager_name' => 'فاطمة علي',
                'manager_phone' => '+963-21-8765432',
                'manager_email' => 'fatima@magicshoe.test',
                'latitude' => 36.2021,
                'longitude' => 37.1343,
                'is_active' => true,
                'opening_time' => '09:00',
                'closing_time' => '22:00',
                'working_days' => ['saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            ],
            [
                'name' => 'فرع حمص',
                'name_ar' => 'فرع حمص',
                'name_en' => 'Homs Branch',
                'address' => 'شارع الدبلان، حمص، سوريا',
                'address_ar' => 'شارع الدبلان، حمص، سوريا',
                'address_en' => 'Al-Dablan Street, Homs, Syria',
                'city' => 'حمص',
                'state' => 'حمص',
                'country' => 'سوريا',
                'postal_code' => '13000',
                'phone' => '+963-31-3456789',
                'email' => 'homs@magicshoe.test',
                'manager_name' => 'خالد حسن',
                'manager_phone' => '+963-31-7654321',
                'manager_email' => 'khaled@magicshoe.test',
                'latitude' => 34.7324,
                'longitude' => 36.7137,
                'is_active' => true,
                'opening_time' => '09:00',
                'closing_time' => '21:00',
                'working_days' => ['saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            ],
            [
                'name' => 'فرع اللاذقية',
                'name_ar' => 'فرع اللاذقية',
                'name_en' => 'Latakia Branch',
                'address' => 'شارع الكورنيش، اللاذقية، سوريا',
                'address_ar' => 'شارع الكورنيش، اللاذقية، سوريا',
                'address_en' => 'Corniche Street, Latakia, Syria',
                'city' => 'اللاذقية',
                'state' => 'اللاذقية',
                'country' => 'سوريا',
                'postal_code' => '35000',
                'phone' => '+963-41-4567890',
                'email' => 'latakia@magicshoe.test',
                'manager_name' => 'سارة أحمد',
                'manager_phone' => '+963-41-6543210',
                'manager_email' => 'sara@magicshoe.test',
                'latitude' => 35.5183,
                'longitude' => 35.7928,
                'is_active' => true,
                'opening_time' => '09:00',
                'closing_time' => '22:00',
                'working_days' => ['saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            ],
            [
                'name' => 'فرع طرطوس',
                'name_ar' => 'فرع طرطوس',
                'name_en' => 'Tartus Branch',
                'address' => 'شارع البحر، طرطوس، سوريا',
                'address_ar' => 'شارع البحر، طرطوس، سوريا',
                'address_en' => 'Sea Street, Tartus, Syria',
                'city' => 'طرطوس',
                'state' => 'طرطوس',
                'country' => 'سوريا',
                'postal_code' => '32000',
                'phone' => '+963-43-5678901',
                'email' => 'tartus@magicshoe.test',
                'manager_name' => 'محمد يوسف',
                'manager_phone' => '+963-43-5432109',
                'manager_email' => 'mohammed@magicshoe.test',
                'latitude' => 34.8886,
                'longitude' => 35.8869,
                'is_active' => true,
                'opening_time' => '09:00',
                'closing_time' => '21:00',
                'working_days' => ['saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            ],
            [
                'name' => 'فرع حماة',
                'name_ar' => 'فرع حماة',
                'name_en' => 'Hama Branch',
                'address' => 'شارع العاصي، حماة، سوريا',
                'address_ar' => 'شارع العاصي، حماة، سوريا',
                'address_en' => 'Al-Asi Street, Hama, Syria',
                'city' => 'حماة',
                'state' => 'حماة',
                'country' => 'سوريا',
                'postal_code' => '14000',
                'phone' => '+963-33-6789012',
                'email' => 'hama@magicshoe.test',
                'manager_name' => 'نور الدين',
                'manager_phone' => '+963-33-4321098',
                'manager_email' => 'nour@magicshoe.test',
                'latitude' => 35.1318,
                'longitude' => 36.7578,
                'is_active' => true,
                'opening_time' => '09:00',
                'closing_time' => '21:00',
                'working_days' => ['saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            ]
        ];
        
        foreach ($branches as $branch) {
            Branch::create($branch);
        }
        
        $this->command->info('✅ تم إنشاء الفروع بنجاح');
    }
}