<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Coupon;
use Carbon\Carbon;

class CouponSeeder extends Seeder
{
    public function run()
    {
        $coupons = [
            [
                'code' => 'WELCOME10',
                'name' => 'خصم ترحيبي 10%',
                'description' => 'خصم 10% على أول طلب لك',
                'type' => 'percentage',
                'value' => 10,
                'minimum_amount' => 100,
                'maximum_discount' => 50,
                'usage_limit' => 100,
                'usage_limit_per_customer' => 1,
                'is_active' => true,
                'is_public' => true,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(3),
                'applicable_products' => null,
                'applicable_categories' => null,
                'excluded_products' => null,
                'excluded_categories' => null,
                'customer_groups' => null,
                'terms_and_conditions' => 'يُطبق على الطلبات التي تزيد قيمتها عن 100 ريال. صالح لمرة واحدة فقط.',
            ],
            [
                'code' => 'SAVE50',
                'name' => 'خصم 50 ريال',
                'description' => 'خصم 50 ريال على الطلبات التي تزيد عن 200 ريال',
                'type' => 'fixed_amount',
                'value' => 50,
                'minimum_amount' => 200,
                'maximum_discount' => null,
                'usage_limit' => 200,
                'usage_limit_per_customer' => 2,
                'is_active' => true,
                'is_public' => true,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(6),
                'applicable_products' => null,
                'applicable_categories' => null,
                'excluded_products' => null,
                'excluded_categories' => null,
                'customer_groups' => null,
                'terms_and_conditions' => 'يُطبق على الطلبات التي تزيد قيمتها عن 200 ريال. يمكن استخدامه مرتين لكل عميل.',
            ],
            [
                'code' => 'FREESHIP',
                'name' => 'شحن مجاني',
                'description' => 'شحن مجاني على جميع الطلبات',
                'type' => 'free_shipping',
                'value' => 0,
                'minimum_amount' => 150,
                'maximum_discount' => null,
                'usage_limit' => null,
                'usage_limit_per_customer' => 1,
                'is_active' => true,
                'is_public' => true,
                'starts_at' => now(),
                'expires_at' => now()->addYear(),
                'applicable_products' => null,
                'applicable_categories' => null,
                'excluded_products' => null,
                'excluded_categories' => null,
                'customer_groups' => null,
                'terms_and_conditions' => 'يُطبق على الطلبات التي تزيد قيمتها عن 150 ريال.',
            ],
            [
                'code' => 'SUMMER25',
                'name' => 'خصم الصيف 25%',
                'description' => 'خصم 25% على جميع المنتجات',
                'type' => 'percentage',
                'value' => 25,
                'minimum_amount' => 50,
                'maximum_discount' => 100,
                'usage_limit' => 500,
                'usage_limit_per_customer' => 3,
                'is_active' => true,
                'is_public' => true,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(2),
                'applicable_products' => null,
                'applicable_categories' => null,
                'excluded_products' => null,
                'excluded_categories' => null,
                'customer_groups' => null,
                'terms_and_conditions' => 'يُطبق على الطلبات التي تزيد قيمتها عن 50 ريال. الحد الأقصى للخصم 100 ريال.',
            ],
            [
                'code' => 'VIP20',
                'name' => 'خصم VIP 20%',
                'description' => 'خصم خاص للعملاء المميزين',
                'type' => 'percentage',
                'value' => 20,
                'minimum_amount' => null,
                'maximum_discount' => null,
                'usage_limit' => 50,
                'usage_limit_per_customer' => 5,
                'is_active' => true,
                'is_public' => false,
                'starts_at' => now(),
                'expires_at' => now()->addYear(),
                'applicable_products' => null,
                'applicable_categories' => null,
                'excluded_products' => null,
                'excluded_categories' => null,
                'customer_groups' => ['vip', 'premium'],
                'terms_and_conditions' => 'خاص بالعملاء المميزين فقط.',
            ],
            [
                'code' => 'NEW100',
                'name' => 'خصم 100 ريال للطلبات الجديدة',
                'description' => 'خصم 100 ريال على الطلبات التي تزيد عن 500 ريال',
                'type' => 'fixed_amount',
                'value' => 100,
                'minimum_amount' => 500,
                'maximum_discount' => null,
                'usage_limit' => 100,
                'usage_limit_per_customer' => 1,
                'is_active' => true,
                'is_public' => true,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(1),
                'applicable_products' => null,
                'applicable_categories' => null,
                'excluded_products' => null,
                'excluded_categories' => null,
                'customer_groups' => null,
                'terms_and_conditions' => 'يُطبق على الطلبات التي تزيد قيمتها عن 500 ريال. صالح لمرة واحدة فقط.',
            ],
            [
                'code' => 'EXPIRED',
                'name' => 'كوبون منتهي الصلاحية',
                'description' => 'كوبون تجريبي منتهي الصلاحية',
                'type' => 'percentage',
                'value' => 15,
                'minimum_amount' => null,
                'maximum_discount' => null,
                'usage_limit' => 10,
                'usage_limit_per_customer' => 1,
                'is_active' => true,
                'is_public' => true,
                'starts_at' => now()->subMonths(2),
                'expires_at' => now()->subMonth(),
                'applicable_products' => null,
                'applicable_categories' => null,
                'excluded_products' => null,
                'excluded_categories' => null,
                'customer_groups' => null,
                'terms_and_conditions' => null,
            ],
            [
                'code' => 'INACTIVE',
                'name' => 'كوبون غير نشط',
                'description' => 'كوبون تجريبي غير نشط',
                'type' => 'fixed_amount',
                'value' => 30,
                'minimum_amount' => null,
                'maximum_discount' => null,
                'usage_limit' => 20,
                'usage_limit_per_customer' => 2,
                'is_active' => false,
                'is_public' => true,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(3),
                'applicable_products' => null,
                'applicable_categories' => null,
                'excluded_products' => null,
                'excluded_categories' => null,
                'customer_groups' => null,
                'terms_and_conditions' => null,
            ],
        ];

        foreach ($coupons as $coupon) {
            Coupon::create($coupon);
        }
    }
}
