<?php

namespace Database\Seeders;

use App\Models\HomePageSection;
use Illuminate\Database\Seeder;

class HomePageSectionSeeder extends Seeder
{
    protected array $sections = [
        [
            'section_key' => 'hero',
            'title_ar' => 'أنيق',
            'title_en' => 'ELEGANT',
            'subtitle_ar' => 'مجوهرات',
            'subtitle_en' => 'JEWELRY',
            'description_ar' => 'مصنوع بدقة. تصاميم خالدة. جودة تدوم لأجيال.',
            'description_en' => 'Crafted with precision. Timeless designs. Quality that lasts generations.',
            'button_text_ar' => 'تسوق الآن',
            'button_text_en' => 'Shop Now',
            'button_link' => '/shop',
            'limit' => 0,
            'settings' => [
                'badge' => 'EST. 2024',
                'cta_primary' => 'Shop Now',
                'cta_primary_link' => '/shop',
                'cta_secondary' => 'View Collection',
                'cta_secondary_link' => '/shop',
                'hero_image' => '/images/img27.png',
                'stats' => [
                    ['value' => '100+', 'label' => 'Designs'],
                    ['value' => '100%', 'label' => 'Quality Guaranteed'],
                ],
            ],
            'sort_order' => 1,
        ],
        [
            'section_key' => 'featured_categories',
            'title_ar' => 'التصنيفات المميزة',
            'title_en' => 'Featured Categories',
            'subtitle_ar' => null,
            'subtitle_en' => null,
            'description_ar' => null,
            'description_en' => null,
            'button_text_ar' => null,
            'button_text_en' => null,
            'button_link' => null,
            'limit' => 5,
            'settings' => null,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'new_arrivals',
            'title_ar' => 'الوافدون الجدد',
            'title_en' => 'New Arrivals',
            'subtitle_ar' => 'أحدث المجموعات',
            'subtitle_en' => 'Latest Collection',
            'description_ar' => 'كن أول من يكتشف أحدث وصولنا',
            'description_en' => 'Be the first to discover our newest arrivals',
            'button_text_ar' => 'عرض الكل',
            'button_text_en' => 'View All',
            'button_link' => '/shop?sort=newest',
            'limit' => 8,
            'settings' => null,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'best_sellers',
            'title_ar' => 'الأكثر مبيعاً',
            'title_en' => 'Best Sellers',
            'subtitle_ar' => 'الأكثر شعبية',
            'subtitle_en' => 'Most Popular',
            'description_ar' => 'اختيارات عملائنا المفضلة',
            'description_en' => "Our customers' favorite picks",
            'button_text_ar' => 'عرض الكل',
            'button_text_en' => 'View All',
            'button_link' => '/shop?sort=bestseller',
            'limit' => 8,
            'settings' => null,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'featured_products',
            'title_ar' => 'المنتجات المميزة',
            'title_en' => 'Featured Products',
            'subtitle_ar' => 'ستايلتو ماجيك شو',
            'subtitle_en' => 'MAGIC SHOE STILETTO',
            'description_ar' => 'تصفح منتجاتنا المميزة',
            'description_en' => 'Browse our featured products',
            'button_text_ar' => 'المزيد',
            'button_text_en' => 'See more',
            'button_link' => '/shop?featured=true',
            'limit' => 6,
            'settings' => [
                'on_sale_title_ar' => 'عروض',
                'on_sale_title_en' => 'ON SALE',
                'on_sale_subtitle_ar' => 'وفر حتى 30% مع ماجيك شو',
                'on_sale_subtitle_en' => 'SAVE UP TO 30% WITH MAGIC SHOE',
                'on_sale_description_ar' => 'تصفح العروض الحالية',
                'on_sale_description_en' => 'Browse our current offers',
                'on_sale_button_text_ar' => 'المزيد',
                'on_sale_button_text_en' => 'See more',
                'on_sale_button_link' => '/shop?onSale=true',
                'on_sale_limit' => 6,
            ],
            'sort_order' => 5,
        ],
        [
            'section_key' => 'why_choose_us',
            'title_ar' => 'لماذا تختارنا',
            'title_en' => 'Why Choose Us',
            'subtitle_ar' => null,
            'subtitle_en' => null,
            'description_ar' => null,
            'description_en' => null,
            'button_text_ar' => null,
            'button_text_en' => null,
            'button_link' => null,
            'limit' => 4,
            'settings' => [
                'features' => [
                    ['icon' => 'Truck', 'title_ar' => 'شحن مجاني', 'title_en' => 'Free Shipping', 'description_ar' => 'شحن مجاني للطلبات فوق 100$', 'description_en' => 'Free shipping on orders over $100'],
                    ['icon' => 'Shield', 'title_ar' => 'جودة مضمونة', 'title_en' => 'Quality Guaranteed', 'description_ar' => 'منتجات أصلية 100% مع ضمان', 'description_en' => '100% authentic products with warranty'],
                    ['icon' => 'RotateCcw', 'title_ar' => 'إرجاع سهل', 'title_en' => 'Easy Returns', 'description_ar' => 'سياسة إرجاع 30 يوم بدون متاعب', 'description_en' => '30-day return policy, hassle-free'],
                    ['icon' => 'HeadphonesIcon', 'title_ar' => 'دعم 24/7', 'title_en' => '24/7 Support', 'description_ar' => 'خدمة عملاء على مدار الساعة', 'description_en' => 'Round-the-clock customer service'],
                ],
            ],
            'sort_order' => 6,
        ],
        [
            'section_key' => 'customer_reviews',
            'title_ar' => 'آراء العملاء',
            'title_en' => 'Customer Reviews',
            'subtitle_ar' => null,
            'subtitle_en' => null,
            'description_ar' => null,
            'description_en' => null,
            'button_text_ar' => null,
            'button_text_en' => null,
            'button_link' => null,
            'limit' => 6,
            'settings' => null,
            'sort_order' => 7,
        ],
        [
            'section_key' => 'latest_blog',
            'title_ar' => 'أحدث المدونة',
            'title_en' => 'Latest Blog',
            'subtitle_ar' => null,
            'subtitle_en' => null,
            'description_ar' => 'هناك العديد من الاختلافات لمقاطع لوريم إيبسوم المتاحة.',
            'description_en' => 'There are many variations of passages of Lorem Ipsum available.',
            'button_text_ar' => null,
            'button_text_en' => null,
            'button_link' => null,
            'limit' => 3,
            'settings' => null,
            'sort_order' => 8,
        ],
        [
            'section_key' => 'newsletter',
            'title_ar' => 'النشرة البريدية',
            'title_en' => 'Newsletter',
            'subtitle_ar' => 'اشترك للحصول على العروض',
            'subtitle_en' => 'Subscribe for offers',
            'description_ar' => null,
            'description_en' => null,
            'button_text_ar' => 'اشترك',
            'button_text_en' => 'Subscribe',
            'button_link' => null,
            'limit' => 0,
            'settings' => null,
            'sort_order' => 9,
        ],
    ];

    public function run(): void
    {
        foreach ($this->sections as $data) {
            HomePageSection::updateOrCreate(
                ['section_key' => $data['section_key']],
                $data
            );
        }
    }
}
